spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:banking
  autoconfigure: # Because we have custom user service we don't need autoconfigured user details service...
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

jwt:
  secret:
    access: HRJjLKV4oOf5AjSEFZIGk4unHBgfymU9BOnsaJUJzkA
    refresh: 7xd2nIuIp49agBVs5Fb0ebkRr6zlGq0cMkZwvDm_BJ8
  expiration:
    access_in_minutes: 5
    refresh_in_days: 14

springdoc:
  swagger-ui:
    url: /api/docs
    path: /swagger-ui
    configUrl: /api/docs/swagger-config
  api-docs:
    path: /api/docs
    default-produces-media-type: application/json
