spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:banking

jwt:
  secret:
    access: HRJjLKV4oOf5AjSEFZIGk4unHBgfymU9BOnsaJUJzkA
    refresh: 7xd2nIuIp49agBVs5Fb0ebkRr6zlGq0cMkZwvDm_BJ8
  expiration:
    access_in_minutes: 5
    refresh_in_days: 14